/**
 * Import full OUI spinout portfolio (238 companies)
 * Source: Oxford University Innovation spinout portfolio
 * 
 * Run with: npx tsx scripts/import-oui-full-portfolio.ts
 * Safe to re-run — all operations use upsert.
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function slugify(text: string): string {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '')
}

const OUI_FULL_PORTFOLIO: Array<{
  name: string
  description: string
  website?: string
  sector: string
  fundingStage: string
  tags: string[]
}> = [
  { name: '1715Labs', description: 'A company being established to commercialise Zooniverse technology', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Adaptimmune', description: 'Crysalin develop a protein lattice technology that is founded on a novel form of highly ordered materials, crysalins, that are produced through modification of naturally occurring protein building blocks.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Aisentia', description: 'Machine learning and AI algorithms.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Aistetic', description: 'A B2B tech platform for clothing retailers to make fit & style accessible to more people, leveraging computer vision, and deep learning. AISTETIC is aiming to reduce online returns and increase conversion for retailers.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Akrivia Health (Cristal Health)', description: '"CRIS" software that enables submission, de-identification and sharing of mental health patient records using a federated data and information governance model.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Alcolizer Technology UK (OxTox)', description: 'Oxtox develops medical devices for the detection of specific drugs in the human system.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Alethiomics', description: 'To develop new methodologies for single cell genomics.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Animal Dynamics', description: 'Animal Dynamics marries fine-engineering skills with a deep understanding of the fundamental mechanisms, to produce revolutionary machines that will change the shape of the future, taking inspiration from our environment in order to protect it, and capable of performance beyond anything currently found in nature or engineering.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Arcube', description: 'Helps airlines boost customer loyalty through personalized, real-time rewards', website: 'https://www.arcube.org/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Argonaut', description: 'DiffBlue is a world leader in automated test generation. Their products have been developed with industry partners over the last ten years and replace the manual process of writing tests.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Ark', description: 'Archiving Services for Big Data', website: 'http://www.arkivum.com/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Ascension Earth Resources', description: 'Harnessing the power of CRISPR to develop the next generation of RNA therapeutics.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Astut', description: 'Astut is developing AI to generate options for high-stakes, unseen decision-making scenarios, focusing on transparent and Explorative AI for complex, one-off decisions. This includes leveraging technologies like generative AI, novelty search, and natural language programming.', sector: 'AI', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Asymmetric Suzuki Reactions (EnantiOx)', description: 'To develop compound libraries based on the asymmetric synthesis methodolofies.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Attest', description: 'Digital platform to make consumer research simple.', website: 'https://www.askattest.com', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'AuC Sensing Ltd', description: 'Sensor development.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Augmented Intelligence Labs', description: 'The company develops analysis and decision support systems for marketing leaders, creating tools which are integrated into those offered by marketing research companies.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Aurox', description: 'Aurox was established to research, develop, manufacture and commercially exploit products in the field of confocal microscopy and automated pathology slide scanners.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Avacta', description: 'Breath analysis.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Blue Field Labs', description: 'Expertise and knowledge regarding data privacy, ethics, data security and public policy in connection with technology use.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Blueberry Life', description: 'Life insurance for those with chronic illnesses.', website: 'https://www.blueberrylife.com', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Bodle Technologies', description: 'Using phase change materials for smart glazing and displays.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Bower Collective', description: 'Sustainable household and personal care products in reusable packaging.', website: 'https://bowercollective.com/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'BreatheOx (Albus Health)', description: 'Development of asthma monitoring system', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'CN Bio Innovations', description: 'Using leading edge human biomimetic platforms to test and develop therapeutics for serious human diseases.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Caeruleus Genomics', description: 'A proprietary multi-omics discovery platform to resolve RNA-centric mechanisms in rare and chronic diseases.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Cella Energy', description: 'Advanced materials and technologies in safe, lightweight, high performance hydrogen storage technology.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Celleron Therapeutics', description: 'Celleron is an oncology healthcare company that has developed biomarkers using epigenetic techniques that match drugs to responsive disease.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Celoxica Ltd', description: 'Software/hardware solutions', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Clinox', description: 'ClinOx offers clients knowledge and expertise in the development, placement, conduct and analysis of early phase oncology clinical trials, with particular emphasis on pharmacokinetic and mechanistic endpoints.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Cocotec', description: 'Cocotec builds software tools, which harness the power of automated formal verification. Its product, the Coco Platform, comes with a powerful software development environment that enables developers to build their software, automatically verify whether it is correct, and then generate high quality reliable code.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Cortex Organics', description: 'Focus on the synthesis of natural products.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Covatic', description: 'A broadcast personalisation engine to revolutionise audience experience.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Curacode', description: 'Cutting edge laser technology company.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Cytox', description: 'Cytox develops a technology platform for tests to identify individuals at risk of cognitive decline, Alzheimer’s disease and other dementias.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Dash Technologies Ltd (sub. of Embedded Solutions)', description: 'Parallel hardware/software design.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'DeepReason.ai', description: 'DeepReason.ai offers a Knowledge Graph Management System that can integrate seamlessly with various enterprise, and public, data sources to perform fast and intelligent reasoning', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Deepmatter (Cronin Group – OAS)', description: 'Oxford Medistress is commercialising a novel in vitro blood test device which aims to provide the first objective, quantitative measurement of stress.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Deontics', description: 'Deontics is software which guides doctors and patients through the scientific and clinical decision making.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Designer Carbon Materials', description: 'Designer Carbon Materials, Developing advanced nanomaterials for a range of applications, including energy harvesting, bio-sensing and quantum nanoelectronics.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Digital Epidemiology Services', description: 'A US non-profit which aims to provide education and tools for preventing public health crises and pandemics and to strengthen global public health preparedness', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'EKB Technology', description: 'EKB Technology commercialises a revolutionary Bioprocessing Technology developed for the use of biological systems such as plant and animal cells and microorganisms to modify, produce or purify chemical intermediates.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Edtopia', description: 'Company developing AI-based learning support applications.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Egregious', description: 'Safeguarding enterprises and organisations against AI-driven deception, misinformation, and digital risks', website: 'https://egregious.ai/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'EndLyz Therapeutics Inc', description: 'The company has been created by the Dementia Discovery Fund. The Company’s mission is to develop disease-modifying therapeutics that restore endo-lysosomal function and abrogate neurodegeneration in Parkinson’s disease and other dementias.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'EnzBond', description: 'EnzBond aims to change the current understanding of enzyme evolution process.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Ergodic', description: 'AI platform for enterprise decision-making', website: 'https://ergodic.ai', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'FinCrime Dynamics', description: 'Powering AI for financial crime prevention', website: 'https://fincrimedynamics.com/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'First Light Fusion (Oxyntix)', description: 'Energy from Fusion.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'FlexSR', description: 'A new approach to automatic speech recognition technology.', sector: 'Other', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Fuel 3D (Eykona)', description: 'Eykona develops state-of-the-art imaging solutions to capture dermal characteristics and shape from the human body.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'G-Nostics', description: 'G-Nostics has identified SNPs that have highly predictive associations with nicotine addiction and therefore tobacco consumption. These SNPs provide a method to help individuals decide which specific smoking cessation methods are most effective for them, offering personalised treatment to the \'smoker\' which significantly increases their chances of quitting.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'GTT Analytics', description: 'Developing international trade and transport simulators, using mathematical models and machine learning.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'GaitQ', description: 'Improving the lives of people living with Parkinson’s.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Global Campus', description: 'Global Campus supports sustainable, integrated and interuniversity learning opportunities, reinvesting profits in scholarships for students and/or building capacity in local heritage structures.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Global Health Research Accelerator CIC', description: 'Aim is to accelerate and streamline research through an innovative digital platform for knowledge sharing.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Global Malaria Vaccinces', description: 'Malaria vaccine development.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Global Pathogen Analysis Service (GPAS)', description: 'GPAS is now part of EIT Pathogena, a cutting-edge genomic analysis platform for academics and public health professionals around the world to help fight infectious diseases.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Glox Therapeutics', description: 'The company is focused on the use of bacteriocins and anti-microbial therapies.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Glycoform', description: 'Glycosolation technology.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Granza Bio Corporation', description: 'A new era in cancer therapeutics by developing personalised and targeted cancer treatments using the body\'s own immune system.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Greater Change', description: 'Personalised cash grants to help people out of homelessness for good. £1,319 spent by Greater Change unlocks £35,177 in cost savings to the government. A return of over 20x.', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'GyreOx', description: 'GryeOx addresses significant unmet need in drug discovery as the IP can make expanded drug libra of macrocycles in the hit to lead stage.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'HEXR (Oxhex)', description: 'Therapeutics biotech company developing proprietary drug delivery platform technology.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Hare Analytics', description: 'Behaviour-based analytics.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'HealthKey', description: 'The integration layer for healthcare access and payments.', website: 'https://www.healthkey.health/', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Helio Display Materials (Heliochrome)', description: 'LED spin-out using Perovskite technology.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'HomeTree', description: 'Helping homeowners transition to low carbon living.', website: 'https://www.hometree.co.uk', sector: 'CleanTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Hoxton', description: 'Occupancy software to help optimize the use of buildings and public spaces.', website: 'https://www.hoxton.ai/home', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Human Centric DD', description: 'To discover significantly de-risked novel drug targets for licensing and in-house development.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'HydRegen', description: 'Cleaner, safer, faster chemical production.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'IXO Therapeutics', description: 'A biotechnology company formed to research and develop novel medicines from natural sources for the treatment of immune-mediated and inflammatory diseases.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'InkPath', description: 'Inkpath is a skills tracking app which helps it\'s users plan and track their career development in a smart format.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Intelligent Ultrasound (Medaphor)', description: 'Intelligent Ultrasound develops and sells products and services that make medical ultrasound imaging a more effective diagnostic tool and help hospitals provide a better quality, more consistent ultrasound imaging service for their patients.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Intrexon (Oxitec)', description: 'Controlling insects that spread disease.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Isogenix', description: 'Company developing a new gene therapy products for the treatment of rare diseases.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'IttyBit', description: 'Simplifying the hosting and handling of media files for developers', website: 'https://ittybit.com', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Ivy Farm', description: 'First commercial producer of sustainable, guilt-free meat.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Kleidox', description: 'Work with major marketing insights companies in order to develop their marketing products.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Kodiform Therapeutics', description: 'Developing small-molecule drugs targeting cancer-linked disordered proteins.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'LiliumX', description: 'LiliumX uses a unique protein technology platform to facilitate scalable discovery of first-in-class bispecific biologics', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'LitHits', description: 'LitHits is a novel way to encourage people to read and engage with literature through their mobile phone via the LitHits app.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'LogMyCare', description: 'Digital platform for the care sector.', website: 'https://www.logmycare.co.uk', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Loop (Nevatas)', description: 'Navetas is a UK based technology company delivering cloud-based energy monitoring and smart data analytics for the connected home.', sector: 'CleanTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Lumai', description: 'Optical neural networks.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'MOA Technology Limited', description: 'The company is developing novel technology with applications in plant protection products.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Machine Discovery', description: 'Development and commercialisation of quantum physics, acceleration and optimisation software for intelligent computational R&D.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Macrocosm', description: 'Modelling the global economy for a sustainable future', sector: 'AI', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Macrophox', description: 'A novel cancer cell therapy company, delivering tumour-targeted expression of anti-cancer biologics.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'MetaBoards', description: 'Ubiquitous wireless power and data using metamaterials.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'MindWeavers', description: 'Computer game language development software.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Minervation', description: 'Web-based healthcare knowledge.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Moneybox', description: 'Savings and investment app helping more than 1m people turn their money into something greater.', website: 'https://www.moneyboxapp.com/', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'MuOx', description: 'Duchenne Muscular Dystrophy.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'NantBio', description: 'Developing treatments using molecularly targeted drugs tailored to the specific molecular profile of a patient\'s tumour.', sector: 'HealthTech', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'NaturalMotion', description: 'Interactive character animation.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Nature-based Insights', description: 'Social enterprise focusing on assessment of the ecological impact of industry supply chain and manufacturing and associated remedations.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'NavLive', description: 'Real-time 3D mapping for construction efficiency', website: 'https://navlive.ai/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Navenio', description: 'A revolutionary new approach to indoor positioning that combines data from mobile phone sensors with map information such as floor plans, and wifi “maps” where available, to give highly accurate location information without the need for any further hardware.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Neu Edge', description: 'Design and manufacture accelerator graphical cards for datacenters.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Neu Health', description: 'Digital health company focused on neurodegenerative diseases.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Ni20', description: 'Developing a brain implant to treat a variety of diseases.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Noggin', description: 'Enabling equitable access to credit.', website: 'https://nogginhq.com/', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Novarc', description: 'Automotive components.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OBS Medical (Oxford BioSignals)', description: 'Vigilance monitoring systems.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'ODQA Renewable Energy Technologies', description: 'Development of geothermal technologies', sector: 'CleanTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OMIA Ltd', description: 'Image analysis.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OMass', description: 'Specialise in applying state-of-the-art mass spectrometry platforms to characterising intact protein assemblies, often referred to as native mass spectrometry.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'ORCA Computing', description: 'building a scalable, modular and flexible quantum computing platform.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OXB (formerly Oxford Biomedica)', description: 'Gene-based therapeutics', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OXDH', description: 'Oxford Digital Innovation encompasses three different products. Two of them are online health records platform which aim to integrate NHS data (Zygote – IVF platform – and Simba – maternity platform). The 3rd platform is a virtual hospital which is aimed at scheduling appointments for patients and enable online consultations in specific specialisations, starting with eye care, skin care, pathology and dental medicine.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OpenClinical', description: 'OpenClinical’s transparent AI care apps present the right pathway for each case, and explain every decision', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Orbit RRI', description: 'Promote a culture of responsible research and innovation in information and communications technology and other areas of technology, research and innovation through its support for, continuation and expansion of the Observatory for Responsible Research and Innovation project.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Orfonyx', description: 'Design oligonucleotide drugs that can activate expression of specific genes using a novel gene regulatory mechanism.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Organox', description: 'The OrganOx metra is the first and only fully automated normothermic liver perfusion device for improved organ preservation. The OrganOx pipeline products will extend the use of their core technology to the preservation of other organs.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Osler Diagnostics (Oxford Impedance Diagnostics)', description: 'Researches, designs and will market diagnostic tests for the measurement of clinical bio markers that reduce healthcare costs and improve patient outcomes.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Outplay', description: 'Free-to-play mobile games.', website: 'http://www.outplay.com/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'OxCCU', description: 'To optimise the catalyst performance and highlight the advantages of a catalyst to create green fuel for the aviation sector through carbon capture.', sector: 'CleanTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxCarbon', description: 'To provide data curation and maintenance services to commercial entities involved in carbon offset markets.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxCo', description: 'OxCo produces videos in collaboration with researchers, teaches academics how to leverage video technologies, and convenes unique hybrid events.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxDx', description: 'To develop and commercialise a rapid non-lab based diagnostic test for viral infections, with the first focus on Covid19.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxEd', description: 'Development of a platform for the standardisation of assetments to facility language, reading and arithmetic skills in children.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxLOD', description: 'To bring the tools developed for heritage to the management of healthcare data.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxLoc', description: 'GPS tracking and monitoring technology.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxMet', description: 'Next generation of high performance alloys.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxProx', description: 'To improve the ESG outcomes of publicly traded corporations by enhancing the efficacy of shareholder ownership rights.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxSight', description: 'The OxSight ‘SmartSpecs’ help sight impaired and blind people to navigate independently, avoid collisions and see in the dark.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxSonics', description: 'OxSonics provide economic and scalable life-changing treatments to solid tumour cancer patients.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxStem', description: 'OxStem is a developer of cell programming therapies.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxSyBio', description: 'Developing 3D printing techniques to produce a range of tissue-like and functional tissues for medical research and clinical applications. Their vision is to ultimately produce tissues that can be used in the clinic for organ repair or replacement.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxVax', description: 'The technology consists of two patent families which collectively enable the development of cost effective, off-the-shelf vaccines based on a proprietary dendritic cell subset for the treatment of solid tumour cancers. The technology overcomes certain key roadblocks previously associated with dendritic cell vaccine technology.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'OxVent', description: 'OxVent Limited is a joint-venture social enterprise that will license the OxVent ventilator design for international deployment in Covid19 and beyond, and provide consultancy on its testing, regulatory approval and manufacturing.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxa (formerly Oxbotica)', description: 'Oxbotica. Robotics, autonomous systems, driverless pods.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxagen Ltd', description: 'Gene/Drug Development', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxbridge Pulsars', description: 'Oxbridge Pulsar Sources (OPS) is researching and developing novel radio transmitting antennas, based on new principles.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxehealth', description: 'Revolutionary healthcare technology that measures medical vital signs without physical contact.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxems', description: 'Oxford Electromagnetic Solutions - smart asset management through underground network visibility.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxepi', description: 'Oxidative Enzymes for the Pulp and Paper Industry.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Advanced Surfaces', description: 'Oxford Advanced Surfaces develops and commercialises advanced materials and technology solutions leveraging breakthrough surface modification technology.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Archdigital', description: 'Genetic Genealogy', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Asymmetry Int. plc', description: 'Drug Development.  Oxford Asymmetry merges  with Evotec BioSystems April 2009.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Biodynamics', description: 'Oxford BioDynamics offers a novel and revolutionary biomarker discovery platform technology in the diagnostics field of aberrant gene expression.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Biomaterials', description: 'Biomimetic spinning of fibres.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Biosensors', description: 'Medical software', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Biotrans', description: 'Develops and commercialises enzymatic process technologies that yield high-value chemical compounds.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Brain Diagnostics', description: 'Software and patented approach to differential diagnosis of cognitive diseases', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Cancer Biomarkers', description: 'Pioneering biomarker technologies for cancer therapies.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Consultants for Social Inclusion', description: 'Oxford Consultants for Social Inclusion (OCSI) helps local government identify deprived neighbourhoods, target resources, evaluate programme effectiveness and strengthen regeneration bids.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Drug Design (Inhibox)', description: 'Screensavers for drug candidates.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Emergent TB Consortium Ltd', description: 'New tuberculosis vaccine – MVA85A.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Green Innotech', description: 'Carbon-free transformation of ammonia waste.', sector: 'CleanTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford HighQ', description: 'Sensor technology based on optical microcavities used in scientific instruments and chemical sensors.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Imaging Detectors', description: 'Developing high performance scientific imaging detectors capable of studying structures and processes at the atomic level.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Instruments plc', description: 'Technology products and services.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Medical Diagnostics', description: 'Oxford Medical Diagnostics develops and supplies breath analysis technologies for rapid, accurate, and low-cost monitoring of diseases and metabolic functions.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Mestar', description: 'A rapidly grown, energetic company specialising in translational and regenerative medicine.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Molecular', description: 'Chemical information management.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Molecular Biosensors Limited', description: 'Development and application of bacterial biosensors for detection and quantification of environmental contamination, including organics and metals, on-site and in real-time.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Multi Spectral', description: 'Develops and manufacturers multispectral digital scanners based upon a patented flatbed scanner design.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Nanopore Technologies', description: 'Oxford Nanopore Technologies is developing and commercialising a new generation of nanopore-based electronic systems for analysis of single molecules, including DNA, RNA and proteins.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Olefins', description: 'Developing novel catalyst process and route to high value internal olefins.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford PV', description: 'Oxford PV are developing new photovoltaic cells that will provide a sustainable solar energy source.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Risk', description: 'Oxford Risk is the market-leading provider of customer risk profilers. Their products reveal the level of risk customers are willing and able to take with their financial investments.', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Science Enterprises', description: 'Invests in transformational science and technology from the University of Oxford.', website: 'https://www.oxfordscienceenterprises.com/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Oxford Simcell', description: 'Produce non-replicating bacterial cells for a variety of healthcare applications.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford Sustainable Fuels', description: 'Catalyst production and processes for upgrading pyrolysis oil to high octane gasoline.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford VR', description: 'Virtual Reality software to help treat people with severe paranoia by allowing them to face situations that they fear.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxford VacMedix', description: 'Cellular immunity vaccines.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxitec (Intrexon)', description: 'Provide an environmentally-responsible method of controlling disease spreading pests.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxomics', description: 'Cancer diagnostics.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxonica', description: 'Advanced materials business which licences patents related to nanomaterials.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxonomy', description: 'Maritime trade and transport simulation.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxsed', description: 'A lean spin-out, social enterprise focusing on developing a fast rapid COVID-19 test. Joint Oxford University and OSCAR company.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxstem Immuno', description: 'A not for profit company providing a solution and accreditation to businesses that work to bring their workforce out of multidimensional poverty', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxtex', description: 'Tissue expander solutions for the primary use in reconstructive and dental surgery.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Oxvalue.ai', description: 'Oxvalue.ai offers a useful new approach for appraising technology, and an important guide for decision-making in technology investment, transfer and commercialisation.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'PATTRN.AI', description: 'Provides advanced insights on global information operations, data flows, and public understanding of critical issues.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'PalaeoPi', description: 'Low cost three dimensional imaging of museum artifacts.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Particle Therapeutics', description: 'Particle Therapeutics is a drug delivery company developing innovative particle formulation and drug delivery technologies to improve the efficacy and administration of a range of pharmaceuticals.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Perspectum Diagnostics', description: 'Developing solutions for major unmet needs in diagnostic medicine in multiple internal organs. In the first instance the focus will be on, the detection and the accurate, quantitative measurement of liver, gallbladder and pancreatic disease, including precancerous and cancerous states in these organs.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Pharminox', description: 'Anti-cancer drugs.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'PhishAR', description: 'Augmented reality cybersecurity assistant.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'PowderJect Pharmaceuticals plc', description: 'Drug/Vaccine Delivery.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Pro-Mapp', description: 'Software enabled system for orthopaedic care pathway management, implant safety monitoring and patient reported outcome delivery.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Profile Textmine', description: 'AI tools to help businesses manage their critical documents.', website: 'https://legislate.ai/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Proxisense', description: 'Proxisense specialise in advanced sensors, diagnostics and optimisation systems to prevent downtime & equipment failure.  They improve performance & efficiency of complex rotating equipment.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Qdot', description: 'High heat flux technology. The company will provide advanced engineering solutions to challenging thermal problems such as those that occur in fusion reactors, or high power density electronic systems.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'QuantrolOx', description: 'Machine learning algorithm and codes for quantum computers.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Quantum Dice', description: 'The company uses quantum mechanics to generate verified truly random numbers.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Quantum Fabrix', description: 'Weaving perfect components into quantum technology solutions.', sector: 'Deep Tech', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Quantum Motion Technologies', description: 'Silicon-based quantum computing.', sector: 'Deep Tech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'RAIQC', description: 'Software to train radiologists.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'RQ Biotechnology', description: 'To develop therapeutic antibodies.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'RQBio Covid', description: 'Developing monoclonal antibodies for instant, long-lasting immunity, protecting vulnerable people from infectious diseases.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'ReOx', description: 'ReOx is a drug discovery company that is building on the primary research of the founding academics to develop novel treatments for disease by controlling the activity of hypoxia inducible factor (HIF).', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Red Sift', description: 'Cybersecurity software to protect small and large businesses.', website: 'http://redsift.io/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Refeyn (Arago Biosciences)', description: 'Developing mass photometry - a revolutionary new way to analyse molecules. It enables the accurate mass measurement of single molecules in solution, in their native state and without the need for labels.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Reg Metrics', description: 'Reg Metrics - Regulatory compliance software, that enables health innovation.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Research Machines plc', description: 'Educational IT.', sector: 'EdTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Riotech', description: 'A biotherapeutics company, established to exploit the work in Viral Hepatitis undertaken at Imperial College, London and at Oxford University through the Wellcome Trust Centre for Human Genetics.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Rogue Interrobang', description: 'Strategy gaming and consultancy', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Run3D', description: 'Offering the most accurate assessment of running biomechanics that modern science is able to provide.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Salunda (Oxford RF Sensors)', description: 'Robust, networked sensors for oilfield machinery, drilling and metering.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Sandymount', description: 'Development and characterisation of novel, first-in-class, selective and potential small molecule inhibitors targeting the YEATS Domain (YD) of MLLT1 and MLLT3.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Scan', description: 'The largest private network for medical scans.', website: 'https://uk.scan.com/', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Scenic Biotech BV', description: 'Exploitation of proprietary ‘Cell seq’ Technology platform', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Semmle', description: 'SemmleCode is a line of products aimed to help developer teams improve their software quality.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'SerenOx', description: 'Aim to deliver rapid diagnosis of inherited blood disorders, infectious diseases and early-stage cancer in sub-Saharan Africa.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Shuffle Finance', description: 'Shuffle Finance provides growth capital to restaurants, repaid through its consumer rewards app.', website: 'https://www.shuffle.finance/', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Singula Bio', description: 'Method for ranking/selecting mitochondrial neoantigens for targeted cell therapy.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Skylark Works', description: 'Harness connections, promote collaboration and deliver practical projects for social impact.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'SnowFox Discovery', description: 'Aims to identify and explore natural hydrogen sources.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Sonosine (Oxford Enhanced Medical Limited)', description: 'Their system uses electromagnetic and acoustic waves to create a new class of medical images at a cost comparable to ultrasound.', sector: 'HealthTech', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Spintex Engineering', description: 'To develop commercially scalable manufacturing process for spinning spider silk.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Spoke', description: 'Online men’s apparel brand', website: 'https://spoke-london.com/', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'SugaROx', description: 'Crop biostimulants for global food security', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Summit Therapeutics', description: 'Chemical genomics.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Summit plc', description: 'Summit Therapeutics is an international biopharmaceutical company focussed on the discovery and development of novel medicines to treat the fatal muscle wasting disease Duchenne muscular dystrophy and infections caused by the bacteria C. difficile.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Synaptica Ltd', description: 'Neurodegenerative diseases.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Synergy Pharmaceuticals', description: 'Pharmaceuticals.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'TDeltaS', description: 'TdeltaS is committed to developing science-based proprietary products that sit at the interface of food and pharmaceuticals - nutraceuticals - and offer real improvement in human physical and mental performance.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'TheraCryf', description: 'Developing innovative therapeutics in oncology and behavioural brain disorders.', sector: 'AI', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Third Phase Ltd', description: 'A software development company that produce clinical trial data.  In 2005 Third Phase Ltd merged with the Cmed Group Ltd.  Third Phase Limited Merges with Cmed Group October 2005.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Tidal – Kepler Energy', description: 'Kepler Energy Limited develops a second-generation tidal turbine, which has the potential to harness tidal energy more efficiently and cheaply, using a device which is simpler, more robust and more scalable than current designs.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'TurinTech', description: 'AI tools for developers to generate and optimise their code', website: 'https://www.turintech.ai', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Vaccitech', description: 'The company has been formed around two viral vector vaccines, one to prevent influenza and the other to treat prostate cancer.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Veer Technologies', description: 'All-in-one recruitment platform with video capacity.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Vivid Dx (formerly Ramanomics)', description: 'Diagnostics built on a Raman-spectroscopy-powered single cell identification for bacteria and fungi.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Wrapidity (Diadem)', description: 'Domain-centric intelligent automated data extraction methodology.', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Wrisk', description: 'Embedded insurance for the automotive sector.', website: 'http://www.wrisk.co', sector: 'FinTech', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Xerion Healthcare', description: 'Nanoparticles for cancer therapy, imaging and drug delivery.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Yasa Motors', description: 'YASA Motors manufactures a highly differentiated advanced axial flux motor and generator based on its proprietary Yokeless And Segmented Armature (YASA™) technology.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Yellowstone Biosciences', description: 'Commercialising T cell receptor-based immunotherapy for multiple indications.', sector: 'Life Sciences', fundingStage: 'Pre-Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Zamma', description: 'Revolutionising digital ID verification for airlines', website: 'https://zamna.com/', sector: 'AI', fundingStage: 'Seed', tags: ['Oxford Capital Partners'] },
  { name: 'Zegami', description: 'Data discovery software to manage and sort collections of images and data visually.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'Zyentia', description: 'Modification of proteins.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'iOx Therapeutics Limited', description: 'Developing a novel cancer immunotherapy discovered through a collaboration between Ludwig Cancer Research and Professor Vincenzo Cerundolo, the director of the MRC Human Immunology Unit within the University of Oxford’s Weatherall Institute of Molecular Medicine.', sector: 'Life Sciences', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
  { name: 'iota Sciences', description: 'Develop technologies that miniaturise fluid handling to accelerate drug discovery.', sector: 'Other', fundingStage: 'Seed', tags: ['Oxford University Innovation', 'Spinout'] },
]

async function main() {
  console.log('Importing full OUI spinout portfolio (238 companies)...\n')

  const oxford = await prisma.university.upsert({
    where: { slug: 'oxford' },
    update: {},
    create: { slug: 'oxford', name: 'University of Oxford' },
  })

  let count = 0
  let skipped = 0
  for (const co of OUI_FULL_PORTFOLIO) {
    const slug = slugify(co.name)
    if (!slug) { skipped++; continue }
    await prisma.company.upsert({
      where: { universityId_slug: { universityId: oxford.id, slug } },
      update: {
        description: co.description,
        tags: co.tags,
        sector: co.sector,
        segment: co.sector,
        fundingStage: co.fundingStage,
        website: co.website ?? null,
        isEcosystemOrg: false,
      },
      create: {
        universityId: oxford.id,
        slug,
        name: co.name,
        description: co.description,
        website: co.website ?? null,
        tags: co.tags,
        sector: co.sector,
        segment: co.sector,
        fundingStage: co.fundingStage,
        isEcosystemOrg: false,
        newThisWeek: false,
      },
    })
    count++
  }
  console.log(`  ✓ ${count} OUI spinout companies imported (${skipped} skipped)`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
